### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by balaji-premkumar** [jonatanklosko/md-collection-pagination#1]
am using this collection-pagination in my code...its shows an error like this..

> Cannot read property 'length' of undefined

can you solve this issue...

**Comment by jonatanklosko** [comment]
Hey @balaji00710, the best approach is to ensure that the `collection` is always an array (i.e. an empty one instead of null). Especially, this should be done during your controller initialization.

Please let me know whether that helps.

**Comment by balaji-premkumar** [comment]
here i am getting the collection of the customers by this service-
![customer](https://cloud.githubusercontent.com/assets/12155194/24605232/a38a64e6-1885-11e7-9304-d9436a013df9.JPG)
Using the service am send the data to page-
![list controller](https://cloud.githubusercontent.com/assets/12155194/24605233/a3e563dc-1885-11e7-846f-8dc8452b392b.JPG)
Here am having the pagination-
![pagination](https://cloud.githubusercontent.com/assets/12155194/24605234/a3ec2b5e-1885-11e7-9a53-8a01e11422c3.JPG)
did you find any issue in the above code...
my json object will be like this...
![json](https://cloud.githubusercontent.com/assets/12155194/24605316/fb9f79fa-1885-11e7-9ac5-3d50c32e1520.JPG)

**Comment by jonatanklosko** [comment]
Did you try adding `$scope.customers = []` to your controller?

**Comment by balaji-premkumar** [comment]
Thanks @jonatanklosko  Its working...
