### ISSUE TITLE
itemsPerPage updating erroneously after changing its value

### ISSUE THREAD

**Issue by felmatias** [jonatanklosko/md-collection-pagination#2]
I've got a pagination problem after I've selected a new itemsPerPage value on a dropdown. After the second page, all my items in collection were being shown.

That problem occurs in the update function (line 190-194). When the code slices the array for the new paginatedCollection, the code was concatenating the offset with the new perPage value (since it was binded to an ng-model).

To solve it, I've just added a parseInt() to the this.perPage variable.

line 193:
this.paginatedCollection = this.collection.slice(offset, offset + parseInt(this.perPage));

That solved for me. If this is the best solution and you want to commit to the code that would be nice!

And thanks a lot for your directive. I was looking for one just like this one!!

**Comment by jonatanklosko** [comment]
Hey @felmatias, thanks for the suggestion. I think it's reasonable to support strings as well. Fixed in 9b62787 and released as 1.0.3
