### ISSUE TITLE
collection list is not reactive

### ISSUE THREAD

**Issue by MileanCo** [jonatanklosko/md-collection-pagination#5]
We are seeing an issue where our data is loaded after the page is loaded, and vm.items is not updating. Can we alter/add more data to "vm.users" after the page has loaded? (need to make API calls to actually GET the data before displaying it).

Our data looks like this (not simply an array of Strings), its an Array of Objects.
```

$scope.playlists = [ 
{name:"asdf", id:"19ahd",}, 
{name:'asdf2', id:'123'},
];
```

**Comment by jonatanklosko** [comment]
Hey, could you provide more details? I checked and it works just fine with updating, see [this demo](https://codepen.io/anon/pen/WOpgrN?editors=1010).

**Comment by jonatanklosko** [comment]
@MileanCo Bump, is this still an issue?

**Comment by jonatanklosko** [comment]
Closing for now, feel free to reopen if this is still an issue and please provide some more information then.
