### ISSUE TITLE
Bower package?

### ISSUE THREAD

**Issue by tarlepp** [jonatanklosko/md-collection-pagination#8]
Seems like this main repo has only `npm` install and not eg, `bower`.

Is there some reason for lacking bower package?

**Comment by jonatanklosko** [comment]
[Someone](https://github.com/horelvis/md-collection-pagination) did a fork and published it on `bower` (I didn't even know about that IIRC). I published this module quite a long time ago, when `npm` already seemed to be more popular than `bower`, so I just decided picked one. If it's a must-have in your case, perhaps you could ask the fork author to update the `bower` package.
